Repository atcollab/at, pull requests merged in 2022-11, with the labels that each got.

#511 Secure the emittance computation in atsummary and ringpara
  atmat/atphysics/ParameterSummaryFunctions/atsummary.m
  atmat/atphysics/ParameterSummaryFunctions/atx.m
  atmat/atphysics/ParameterSummaryFunctions/ringpara.m
Labels: Matlab

#515 Improve patpass
  pyat/at/tracking/patpass.py
  pyat/at/tracking/track.py
Labels: enhancement, Python

#520 Upgrade scipy requirement to 1.4.0
  githubproject.toml
  pyproject.toml
Labels: Python

#523 Python 3.11
  .github/workflows/python-tests.yml
  githubproject.toml
  pyproject.toml
Labels: Python

#519 Elemrnt rotations
  pyat/at/lattice/utils.py
Labels: enhancement, Python

#516 Multibunch Beamloading
  atintegrators/BeamLoadingCavityPass.c
  atintegrators/CavityPass.c
  atintegrators/CorrectorPass.c
  atintegrators/GWigSymplecticPass.c
  atintegrators/GWigSymplecticRadPass.c
  atintegrators/IdTablePass.c
  atintegrators/IdentityPass.c
  atintegrators/ImpedanceTablePass.c
  atintegrators/QuadLinearPass.c
  atintegrators/RFCavityPass.c
  atintegrators/SolenoidLinearPass.c
  atintegrators/ThinMPolePass.c
  atintegrators/VariableThinMPolePass.c
  atintegrators/atimplib.c
  atintegrators/attrackfunc.c
  atintegrators/gwig.c
  atintegrators/gwigR.c
  atintegrators/interpolate.c
  atmat/attests/pytests.m
  pyat/at/collective/__init__.py
  pyat/at/collective/beam_loading.py
  pyat/at/collective/haissinski.py
  pyat/at/collective/wake_elements.py
  pyat/at/collective/wake_object.py
  pyat/at/lattice/elements.py
  pyat/at/lattice/lattice_object.py
  pyat/at/physics/energy_loss.py
  pyat/examples/CollectiveEffects/BeamLoading.py
  pyat/examples/CollectiveEffects/LongDistribution.py
  pyat/examples/CollectiveEffects/RobinsonInstability.py
Labels: enhancement, Python, C

#521 Beam monitor
  atintegrators/BeamMomentsPass.c
  pyat/at/lattice/elements.py
  pyat/at/tracking/track.py
Labels: Python, C

#513 random generators compatibility with parallel processing
  atintegrators/VariableThinMPolePass.c
  atintegrators/atrandom.c
  atintegrators/attypes.h
  atmat/attrack/atpass.c
  docs/p/api/at.tracking.atpass.rst
  pyat/at.c
  pyat/at/cconfig.c
  pyat/at/lattice/__init__.py
  pyat/at/lattice/options.py
  pyat/at/tracking/__init__.py
  pyat/at/tracking/patpass.py
  pyat/at/tracking/track.py
  setup.py
Labels: Matlab, Python
