Repository atcollab/at, pull requests merged in 2022-10, with the labels that each got.

#501 Introduce an RF frequency shift input to specify off-momentum computation
  atmat/atphysics/LinearOptics/atlinopt4.m
  atmat/atphysics/LinearOptics/atlinopt6.m
  atmat/atphysics/LinearOptics/findm44.m
  atmat/atphysics/LongitudinalDynamics/atsetcavity.m
  atmat/atphysics/Orbit/findorbit.m
  atmat/atphysics/Orbit/findorbit4.m
  atmat/atphysics/Orbit/findsyncorbit.m
  atmat/atphysics/TuneAndChromaticity/tunechrom.m
  atmat/attests/pytests.m
  atmat/atutils/getdparg.m
  pyat/test_matlab/test_cmp_linopt6.py
Labels: enhancement, Matlab

#504 quantpass bugfixes
  atintegrators/BndMPoleSymplectic4QuantPass.c
  atintegrators/StrMPoleSymplectic4QuantPass.c
  atintegrators/atquantlib.c
Labels: Matlab, Python, bug fix

#507 Take "QuantPass" into account when checking 6D motion
  atmat/atphysics/Radiation/atdisable_6d.m
  atmat/atphysics/Radiation/atenable_6d.m
  atmat/lattice/atparamscan.m
  pyat/at/lattice/elements.py
Labels: Matlab, Python, bug fix

#505 Introduce an RF frequency shift input to specify off-momentum computation
  docs/conf.py
  pyat/at/lattice/lattice_object.py
  pyat/at/lattice/utils.py
  pyat/at/physics/linear.py
  pyat/at/physics/matrix.py
  pyat/at/physics/orbit.py
  pyat/at/physics/revolution.py
  pyat/test_matlab/test_cmp_physics.py
Labels: enhancement, Python
