Repository atcollab/at, pull requests merged in 2022-04, with the labels that each got.

#372 Set the default cavity PassMethod to RFCavityPass
  atmat/atcavityon.m
  atmat/atphysics/LongitudinalDynamics/atsetcavity.m
  atmat/atphysics/LongitudinalDynamics/cavityon.m
  atmat/atphysics/Orbit/findorbit6.m
  atmat/atphysics/Radiation/atradon.m
  atmat/lattice/Converters/readmad.m
  atmat/lattice/element_creation/atdampMatElem.m
  atmat/lattice/element_creation/atrfcavity.m
  atmat/pubtools/calc_Touschek.m
  atmat/pubtools/calc_dppAperture.m
  atmat/pubtools/lattice_tools/sext_sens_scan.m
  machine_data/sp3v81f.m
  machine_data/spear2rad.m
  machine_data/spear3.m
  pyat/at/lattice/elements.py
  pyat/at/lattice/lattice_object.py
  pyat/at/physics/fastring.py
  pyat/at/physics/orbit.py
Labels: Matlab, Python, bug fix

#396 Resolve conflict with a Matlab toolbox
  atmat/atplot/atplot.m
  atmat/atplot/plotfunctions/plBeamSize.m
  atmat/atplot/plotfunctions/plClosedOrbit.m
  atmat/atplot/plotfunctions/plEmitContrib.m
  atmat/atplot/plotfunctions/plotB0curlyh.m
  atmat/atplot/plotfunctions/plotbetadisp.m
  atmat/atplot/plotfunctions/plotbetadispcurlyh.m
  atmat/atplot/plotfunctions/plotsqrtbetadispcurlyh.m
  atmat/atutils/opticsoptions.m
Labels: Matlab

#393 Energy loss tracking
  pyat/at/physics/energy_loss.py
  pyat/at/physics/radiation.py
Labels: Python, bug fix

#400 Avoid problems with GitHub Windows runners
  .github/workflows/python-tests.yml
  pyat/at.c
  pyat/at/load/utils.py
Labels: Python, bug fix

#351 Lifetime and DA calculations for pyAT
  pyat/at/__init__.py
  pyat/at/acceptance/__init__.py
  pyat/at/acceptance/acceptance.py
  pyat/at/acceptance/boundary.py
  pyat/at/acceptance/touschek.py
  pyat/at/plot/__init__.py
  pyat/at/plot/standalone.py
  pyat/test/test_acceptance.py
Labels: Python

#401 Initialisation of the harmonic number
  pyat/at/lattice/lattice_object.py
Labels: Python, bug fix
