Repository atcollab/at, pull requests merged in 2022-02, with the labels that each got.

#354 atsetcavity accepts dp and dct arguments
  atmat/Contents.m
  atmat/at.m
  atmat/atphysics/LongitudinalDynamics/atsetcavity.m
  atmat/atphysics/Radiation/atradoff.m
Labels: Matlab

#362 Fix WakeElement
  atintegrators/WakeFieldPass.c
  atintegrators/atelem.c
  pyat/Examples/CollectiveEffects/RobinsonInstability.py
  pyat/at/collective/__init__.py
  pyat/at/collective/wake_elements.py
  pyat/at/collective/wake_object.py
  pyat/at/tracking/__init__.py
Labels: Matlab, Python, bug fix

#367 Default particle
  atintegrators/attypes.h
  pyat/at.c
  pyat/at/lattice/lattice_object.py
  pyat/at/lattice/particle_object.py
  pyat/at/physics/orbit.py
  pyat/at/physics/revolution.py
  pyat/at/tracking/__init__.py
  pyat/at/tracking/patpass.py
  pyat/at/tracking/track.py
  pyat/test/test_atpass.py
  pyat/test/test_lattice_object.py
Labels: Python

#368 Energy and particle available to C integrators
  atmat/atmexall.m
  atmat/attrack/atpass.c
  atmat/attrack/atpass.m
  atmat/attrack/coptions.c
  atmat/attrack/linepass.m
  atmat/attrack/ringpass.m
  atmat/atutils/atoptions.m
  atmat/lattice/atCheckRingProperties.m
  atmat/lattice/atfindparam.m
  atmat/lattice/atlocateparam.m
  atoctave/atmexall.m
Labels: Matlab

#371 Custom elements
  pyat/at/load/utils.py
  pyat/test/test_load_utils.py
Labels: Python

#364 Allow setting "dp" in 6D linear optics
  atmat/Contents.m
  atmat/atphysics/LinearOptics/atlinopt6.m
  atmat/atphysics/LinearOptics/findm44.m
  atmat/atphysics/LinearOptics/findm66.m
  atmat/atphysics/LongitudinalDynamics/atsetcavity.m
  atmat/atphysics/ParameterSummaryFunctions/ringpara.m
  atmat/atphysics/Radiation/atenergy.m
  atmat/atphysics/TuneAndChromaticity/tunechrom.m
  atmat/atplot/atbaseplot.m
  atmat/atplot/atplot.m
  atmat/atplot/plotfunctions/plBeamSize.m
  atmat/atplot/plotfunctions/plClosedOrbit.m
  atmat/atplot/plotfunctions/plEmitContrib.m
  atmat/atplot/plotfunctions/plotB0curlyh.m
  atmat/atplot/plotfunctions/plotbetadisp.m
  atmat/atplot/xplot.m
  atmat/attrack/linepass.m
  atmat/attrack/ringpass.m
  atmat/atutils/atoptions.m
  atmat/atutils/getcavptsarg.m
  atmat/atutils/getdparg.m
  atmat/atutils/linoptions.m
  atmat/atutils/wrapper6d.m
  atmat/lattice/atSetRingProperties.m
  atmat/lattice/atfindparam.m
  atmat/lattice/atfitchrom.m
  atmat/lattice/atfittune.m
Labels: enhancement, Matlab

#375 Fix atplot when energy is undefined
  atmat/atphysics/Radiation/atenergy.m
  atmat/lattice/atfindparam.m
Labels: Matlab, bug fix

#361 Haissinski solver for short range wake
  pyat/Examples/CollectiveEffects/LongDistribution.py
  pyat/at/collective/Haissinski.py
  pyat/at/collective/wake_functions.py
Labels: Python
