Repository atcollab/at, pull requests merged in 2022-12, with the labels that each got.

#524 Unfold beam
  pyat/at/tracking/__init__.py
  pyat/at/tracking/track.py
  pyat/at/tracking/utils.py
Labels: enhancement, Python

#531 Update at.beam
  docs/p/howto/Primer.rst
  pyat/at/tracking/particles.py
Labels: Python

#532 Use the ct coordinate in the variable multipole pass method
  atintegrators/VariableThinMPolePass.c
Labels: Matlab, Python

#534 Update quantum diffusion pass methods
  atintegrators/BndMPoleSymplectic4QuantPass.c
  atintegrators/QuantDiffPass.c
  atintegrators/StrMPoleSymplectic4QuantPass.c
  atintegrators/VariableThinMPolePass.c
  atintegrators/atquantlib.c
  atintegrators/atrandom.c
Labels: Matlab, Python

#527 Update examples (+ bug fix)
  atintegrators/BeamLoadingCavityPass.c
  atintegrators/BeamMomentsPass.c
  pyat/at/collective/haissinski.py
  pyat/at/collective/wake_functions.py
  pyat/at/collective/wake_object.py
  pyat/examples/CollectiveEffects/BeamLoading.py
  pyat/examples/CollectiveEffects/LCBI_analyse.py
  pyat/examples/CollectiveEffects/LCBI_run.py
  pyat/examples/CollectiveEffects/LongDistribution.py
  pyat/examples/CollectiveEffects/RobinsonInstability.py
  pyat/examples/CollectiveEffects/TRW_analyse.py
  pyat/examples/CollectiveEffects/TRW_run.py
Labels: Python

#539 Collective unit tests
  pyat/test/test_collective.py
Labels: Python

#541 New plot_sigma() plotting function
  pyat/at/lattice/utils.py
  pyat/at/plot/standalone.py
Labels: enhancement, Python

#542 Stub files for C extensions
  pyat/at.c
  pyat/at/cconfig.pyi
  pyat/at/lattice/options.py
  pyat/at/physics/__init__.py
  pyat/at/physics/diffmatrix.pyi
  pyat/at/tracking/__init__.py
  pyat/at/tracking/atpass.pyi
  pyat/at/tracking/patpass.py
  pyat/at/tracking/track.py
Labels: Python

#545 relax chromaticity test for numpy 1.24
  pyat/test/test_linopt6.py
Labels: Python
