Repository atcollab/at, pull requests merged in 2023-02, with the labels that each got.

#563 do not split elements with IdTablePass method
  atmat/atplot/xplot.m
Labels: Matlab, bug fix

#550 Fix bug in convolve_wakefun
  pyat/at/collective/wake_functions.py
Labels: Python

#556 Frequency Analysis
  pyat/at/physics/__init__.py
  pyat/at/physics/frequency_maps.py
Labels: enhancement, Python
