Repository atcollab/at, pull requests merged in 2023-07, with the labels that each got.

#625 Fix at disable_6d
  atmat/atphysics/Radiation/getclass_6d.m
Labels: Matlab, bug fix

#627 Fix the creation of .mat files
  pyat/at/lattice/elements.py
Labels: Python, bug fix

#597 pyat ReadWrite Insertion Devices into mat files
  atmat/lattice/at2str.m
  atmat/lattice/atguessclass.m
  atmat/lattice/element_creation/atinsertiondevicekickmap.m
  atmat/pubtools/create_elems/atidtable_dat.m
  pyat/at/lattice/idtable_element.py
  pyat/at/load/utils.py
Labels: enhancement

#626 Remove a deprecation warning in numpy 1.25
  pyat/at/physics/linear.py
Labels: Python, bug fix

#638 Remove the warning when calling plot_beta in transfer line mode
  pyat/at/plot/specific.py
Labels: Python, bug fix

#632 Introduction of an "energy loss" element
  atintegrators/EnergyLossRadPass.c
  atmat/atphysics/ParameterSummaryFunctions/atsummary.m
  atmat/atphysics/ParameterSummaryFunctions/ringpara.m
  atmat/atphysics/Radiation/ElossRadiation.m
  atmat/atphysics/Radiation/atdisable_6d.m
  atmat/atphysics/Radiation/atenable_6d.m
  atmat/atphysics/Radiation/atgetU0.m
  atmat/atphysics/Radiation/getclass_6d.m
  atmat/lattice/at2str.m
  atmat/lattice/atguessclass.m
  atmat/lattice/element_creation/atenergyloss.m
  pyat/at/lattice/elements.py
  pyat/at/lattice/lattice_object.py
  pyat/at/physics/energy_loss.py
  pyat/at/physics/matrix.py
  pyat/at/physics/radiation.py
Labels: enhancement, Matlab, Python, C
