Repository atcollab/at, pull requests merged in 2023-10, with the labels that each got.

#657 New Matlab function atsimplering
  atmat/Contents.m
  atmat/at.m
  atmat/atphysics/Radiation/atdisable_6d.m
  atmat/atphysics/Radiation/atenable_6d.m
  atmat/atphysics/Radiation/getclass_6d.m
  atmat/lattice/atsimplering.m
  atmat/lattice/element_creation/atSimpleQuantDiff.m
Labels: enhancement, Matlab

#659 Update of the build process
  .github/workflows/build-python-wheels.yml
  .github/workflows/docs.yml
  .github/workflows/matlab-tests.yml
  .github/workflows/python-tests.yml
  githubproject.toml
  pyproject.toml
Labels: enhancement, Python

#669 Documentation fixes
  docs/p/api/at.tracking.patpass.rst
  pyat/at/lattice/idtable_element.py
  pyat/at/physics/linear.py
  pyat/at/tracking/track.py
Labels: Python, bug fix

#586 Add passive beamloading cavity
  atintegrators/BeamLoadingCavityPass.c
  atintegrators/atimplib.c
  atintegrators/attrackfunc.c
  pyat/at/collective/beam_loading.py
  pyat/examples/CollectiveEffects/BeamLoading.py
  pyat/test/test_collective.py
Labels: enhancement, Python

#658 Optimize atimplib
  atintegrators/BeamLoadingCavityPass.c
  atintegrators/WakeFieldPass.c
  atintegrators/atelem.c
  atintegrators/atimplib.c
  pyat/at/collective/beam_loading.py
  pyat/at/collective/wake_elements.py
Labels: enhancement, Python, C

#667 Bug fix in atgeometry
  atmat/Contents.m
  atmat/at.m
  atmat/lattice/survey/atgeometry.m
  pyat/at/lattice/utils.py
Labels: Matlab, Python, bug fix
