Repository atcollab/at, pull requests merged in 2023-12, with the labels that each got.

#699 Add vbeam vgen vbunch buffers for beam loading element
  atintegrators/BeamLoadingCavityPass.c
  pyat/at/collective/beam_loading.py
Labels: WIP, Python

#713 bugfix in rotation angles and improved help of rotate_elem
  pyat/at/lattice/utils.py
Labels: Python, bug fix

#720 Fix a few "simple ring" problems
  pyat/at/lattice/elements.py
  pyat/at/load/utils.py
  pyat/at/physics/fastring.py
Labels: Python, bug fix

#704 Support of python 3.12, 64-bit wheels only
  .github/workflows/build-python-wheels.yml
  .github/workflows/python-tests.yml
  pyproject.toml
Labels: Python

#723 Corrected documentation errors on PolynomA/B
  pyat/at/lattice/elements.py
Labels: Python, bug fix

#719 Update atsimplering in Matlab
  atmat/atphysics/Radiation/atdisable_6d.m
  atmat/atphysics/Radiation/atenable_6d.m
  atmat/atphysics/Radiation/atgetU0.m
  atmat/atphysics/Radiation/getclass_6d.m
  atmat/lattice/atguessclass.m
  atmat/lattice/atsimplering.m
  atmat/lattice/element_creation/atSimpleQuantDiff.m
Labels: enhancement, Matlab, bug fix
