Repository atcollab/at, pull requests merged in 2023-08, with the labels that each got.

#608 New interface to tracking functions
  pyat/at/acceptance/boundary.py
  pyat/at/physics/energy_loss.py
  pyat/at/physics/linear.py
  pyat/at/physics/matrix.py
  pyat/at/physics/nonlinear.py
  pyat/at/physics/orbit.py
  pyat/at/physics/radiation.py
  pyat/at/physics/revolution.py
  pyat/at/plot/specific.py
  pyat/at/tracking/__init__.py
  pyat/at/tracking/deprecated.py
  pyat/at/tracking/patpass.py
  pyat/at/tracking/track.py
  pyat/at/tracking/utils.py
  pyat/examples/CollectiveEffects/BeamLoading.py
  pyat/examples/CollectiveEffects/LCBI_run.py
  pyat/examples/CollectiveEffects/LongDistribution.py
  pyat/examples/CollectiveEffects/RobinsonInstability.py
  pyat/examples/CollectiveEffects/TRW_run.py
  pyat/test/test_basic_elements.py
  pyat/test/test_collective.py
  pyat/test/test_integrators.py
  pyat/test/test_patpass.py
  pyat/test/test_physics.py
  pyat/test/test_track.py
  pyat/test_matlab/test_cmp_atpass.py
Labels: enhancement, Python

#641 Display the name of selected elements in plots
  pyat/at/plot/generic.py
  pyat/at/plot/specific.py
  pyat/at/plot/synopt.py
Labels: enhancement, Python

#645 Repair the Matlab tests
  pyat/test_matlab/test_cmp_atpass.py
  pyat/test_matlab/test_cmp_linopt6.py
Labels: bug fix

#644 Chromatic functions extended
  pyat/at/physics/linear.py
Labels: enhancement, Python

#640 Don't automatically cache the location of RF cavities
  atmat/Contents.m
  atmat/at.m
  atmat/atphysics/LongitudinalDynamics/atsetcavity.m
  atmat/lattice/atparamscan.m
  developer/matlab/howtos/CavityControl.mlx
  docs/atdocs/matlab/howtos/CavityControl.html
  docs/p/howto/CavityControl.rst
Labels: Matlab, bug fix

#648 Correct the axis definition in plot_sigma
  pyat/at/lattice/axisdef.py
  pyat/at/plot/standalone.py
Labels: Python, bug fix
