Repository atcollab/at, pull requests merged in 2023-06, with the labels that each got.

#604 atreduce: check entrance and exit angles in bends
  atmat/lattice/atreduce.m
Labels: Matlab, bug fix

#617 Documentation of plot_beta
  pyat/at/plot/generic.py
  pyat/at/plot/specific.py
Labels: Python

#613 Harmonic analysis
  pyat/at/physics/frequency_maps.py
  pyat/at/physics/harmonic_analysis.py
  pyat/at/physics/linear.py
  pyat/test/test_physics.py
Labels: enhancement, Python

#615 Matching fixes
  pyat/at/matching/matching.py
  pyat/at/physics/linear.py
Labels: Python, bug fix

#616 Release 0.4.0
  pyat/developers.rst
Labels: Python
