Repository atcollab/at, pull requests merged in 2023-11, with the labels that each got.

#581 New integrators: ExactDriftPass, ExactMultipolePass
  atintegrators/BendLinearPass.c
  atintegrators/ExactDriftPass.c
  atintegrators/ExactHamiltonianPass.cc
  atintegrators/ExactMultipolePass.c
  atintegrators/ExactMultipoleRadPass.c
  atintegrators/ExactRectBendPass.c
  atintegrators/ExactRectBendRadPass.c
  atintegrators/ExactRectangularBendPass.c
  atintegrators/ExactRectangularBendRadPass.c
  atintegrators/ExactSectorBendPass.c
  atintegrators/ExactSectorBendRadPass.c
  atintegrators/atelem.c
  atintegrators/exactbend.c
  atintegrators/exactbendfringe.c
  atintegrators/exactdrift.c
  atintegrators/exactkickrad.c
  atintegrators/exactmultipolefringe.c
  atmat/lattice/element_creation/atrbendtune.m
  docs/common/about.md
  docs/common/ex_passmethods.md
  docs/common/indx.rst
  docs/common/passmethods.md
  docs/common/sa_passmethods.md
  docs/conf.py
  docs/index.rst
  docs/p/index.rst
  pyat/at/lattice/__init__.py
  pyat/at/lattice/elements.py
  pyat/at/lattice/rectangular_bend.py
Labels: enhancement, Matlab, Python

#681 parallelize get_tunes_harmonic
  pyat/at/physics/frequency_maps.py
  pyat/at/physics/harmonic_analysis.py
  pyat/at/tracking/track.py
Labels: enhancement, Python

#690 removes ByError from sbend help in matlab
  atintegrators/sbend.m
Labels: Matlab

#685 feat: compute longitudinal RDT fluctuations.
  atmat/atphysics/NonLinearDynamics/RDTbuildupFluct.m
  atmat/atphysics/NonLinearDynamics/RDTfluctuationIndicator.m
  atmat/atphysics/NonLinearDynamics/computeRDTfluctuation.m
Labels: enhancement, Matlab

#691 Update and centralize the C constants
  atintegrators/BeamLoadingCavityPass.c
  atintegrators/BndMPoleSymplectic4E2Pass.c
  atintegrators/BndMPoleSymplectic4E2RadPass.c
  atintegrators/BndMPoleSymplectic4Pass.c
  atintegrators/BndMPoleSymplectic4QuantPass.c
  atintegrators/BndMPoleSymplectic4RadPass.c
  atintegrators/BndStrMPoleSymplectic4Pass.c
  atintegrators/CavityPass.c
  atintegrators/DeltaQPass.c
  atintegrators/ExactMultipolePass.c
  atintegrators/ExactMultipoleRadPass.c
  atintegrators/ExactRectBendPass.c
  atintegrators/ExactRectBendRadPass.c
  atintegrators/ExactRectangularBendPass.c
  atintegrators/ExactRectangularBendRadPass.c
  atintegrators/ExactSectorBendPass.c
  atintegrators/ExactSectorBendRadPass.c
  atintegrators/RFCavityPass.c
  atintegrators/StrMPoleSymplectic4Pass.c
  atintegrators/StrMPoleSymplectic4QuantPass.c
  atintegrators/StrMPoleSymplectic4RadPass.c
  atintegrators/VariableThinMPolePass.c
  atintegrators/atconstants.h
  atintegrators/atimplib.c
  atintegrators/atrandom.c
  atintegrators/attrackfunc.c
  atintegrators/driftkickrad.c
  atintegrators/exactkickrad.c
  pyat/test/test_physics.py
Labels: Matlab, Python

#693 Python release 0.5.0
  INSTALL.md
  README.md
Labels: Python

#701 Fix a regression bug in AtGetRingProperties
  atmat/lattice/atGetRingProperties.m
Labels: Matlab, bug fix

#706 use np.float64 instead of np.float in function get_bunch_length_espread of pyat/at/acceptance/touschek.py module
  pyat/at/acceptance/touschek.py
Labels: Python, bug fix

#711 Added KStep and HStep keyword arguments to fit_tune and fit_chrom
  pyat/at/matching/globalfit.py
Labels: enhancement, Python

#707 return ZERO acceptance if no tracked particle survives in at/pyat/acceptance/boundary.py
  pyat/at/acceptance/boundary.py
Labels: Python
