Repository atcollab/at, pull requests merged in 2024-12, with the labels that each got.

#859 Set "periodicity" to 1 by default
  pyat/at/lattice/lattice_object.py
  pyat/at/load/matfile.py
  pyat/test/test_lattice_object.py
Labels: Python

#861 Update GitHub actions
  .github/workflows/build-python-wheels.yml
  .github/workflows/docs.yml
  .github/workflows/documentation.yml
  .github/workflows/matlab-tests.yml
  .github/workflows/python-tests.yml
  .readthedocs.yaml
  pyproject.toml
Labels: enhancement, Python

#863 Fix diffusion_matrix compilation on Linux
  atmat/atmexall.m
Labels: Matlab, bug fix

#821 Compute RDTs
  atmat/atphysics/atavedata.m
  pyat/at/physics/__init__.py
  pyat/at/physics/linear.py
  pyat/at/physics/rdt.py
  pyat/test/test_physics.py
Labels: enhancement, Python

#806 New matching
  docs/p/examples.rst
  docs/p/notebooks/observables.ipynb
  docs/p/notebooks/test_variables.ipynb
  docs/p/notebooks/variables.ipynb
  pyat/at/deprecated.py
  pyat/at/future.py
  pyat/at/latticetools/__init__.py
  pyat/at/latticetools/matching.py
  pyat/at/latticetools/observablelist.py
  pyat/at/latticetools/observables.py
  pyat/at/matching/matching.py
  pyat/test/test_legacy_matching.py
  pyat/test/test_matching.py
Labels: enhancement, Python

#870 Fix ohmienvelope with wigglers
  atmat/atphysics/Radiation/atdiffmat.m
  pyat/at/physics/radiation.py
Labels: Matlab, Python, bug fix

#874 adds Multipole class to `atdisable_6d` `atenable_6d`
  atmat/atphysics/Radiation/atdisable_6d.m
  atmat/atphysics/Radiation/atenable_6d.m
Labels: Matlab, bug fix

#875 Set the wiggler indivisible
  atmat/atplot/xplot.m
  pyat/at/lattice/elements.py
Labels: Python, bug fix

#877 Fix the energy loss computation
  .github/workflows/python-tests.yml
  atmat/atphysics/Radiation/atgetU0.m
  atmat/attests/pytests.m
  pyat/at/physics/energy_loss.py
  pyat/at/physics/orbit.py
  pyat/test/test_physics.py
Labels: Matlab, Python, bug fix
