Repository atcollab/at, pull requests merged in 2024-05, with the labels that each got.

#764 make_copy decorator not working for lattice defined as list
  pyat/at/lattice/utils.py
  pyat/at/tracking/utils.py
Labels: bug, Python

#700 Variables
  atintegrators/atelem.c
  docs/conf.py
  docs/p/index.rst
  docs/p/notebooks/variables.ipynb
  pyat/at/future.py
  pyat/at/lattice/__init__.py
  pyat/at/lattice/axisdef.py
  pyat/at/lattice/elements.py
  pyat/at/lattice/lattice_object.py
  pyat/at/lattice/lattice_variables.py
  pyat/at/lattice/utils.py
  pyat/at/lattice/variables.py
Labels: enhancement, Python

#765 Bug in piwinski touschek scattering B2 term
  pyat/at/acceptance/touschek.py
Labels: Python, bug fix

#766 Save and load lattices in JSON format
  atmat/lattice/atdivelem.m
  atmat/lattice/atloadlattice.m
  atmat/lattice/atwritejson.m
  pyat/at/lattice/elements.py
  pyat/at/load/__init__.py
  pyat/at/load/allfiles.py
  pyat/at/load/elegant.py
  pyat/at/load/json.py
  pyat/at/load/matfile.py
  pyat/at/load/reprfile.py
  pyat/at/load/tracy.py
  pyat/at/load/utils.py
  pyat/test/test_basic_elements.py
  pyat/test/test_load_save.py
  pyat/test/test_load_utils.py
Labels: enhancement, Matlab, Python
