Repository atcollab/at, pull requests merged in 2024-08, with the labels that each got.

#809 Add tune resonances plot
  pyat/at/plot/__init__.py
  pyat/at/plot/resonances.py
Labels: enhancement, Python

#812 Always attempt to import at.plot
  docs/m/index.rst
  docs/p/howto/Installation.rst
  docs/p/howto/Primer.rst
  pyat/at/__init__.py
  pyat/at/plot/__init__.py
Labels: Python

#819 update AT matlab help default pass method in atthinmultipole
  atmat/lattice/element_creation/atthinmultipole.m
Labels: enhancement, Matlab

#801 check len(refpts) > 2 after removing zero length elements in get_lifetime()
  atintegrators/atimplib.c
  pyat/at/acceptance/touschek.py
Labels: enhancement, Python

#811 Track all refpts in one track function call in acceptance calculations
  pyat/at/acceptance/acceptance.py
  pyat/at/acceptance/boundary.py
  pyat/at/acceptance/touschek.py
Labels: enhancement, Python

#759 Bug Fix: Wiggler diffusion matrix
  .gitignore
  atintegrators/GWigSymplecticPass.c
  atintegrators/GWigSymplecticRadPass.c
  atintegrators/gwigR.c
  atmat/atphysics/Radiation/FDW.c
  atmat/atphysics/Radiation/FDW.m
  atmat/atphysics/Radiation/ohmienvelope.m
  docs/common/sa_passmethods.md
Labels: Matlab, bug fix, C

#815 Add feeddown polba
  pyat/at/physics/__init__.py
  pyat/at/physics/magnet_tools.py
Labels: enhancement, Python
