Repository atcollab/at, pull requests merged in 2024-06, with the labels that each got.

#774 Fix a regression bug in atavedata
  atmat/atphysics/atavedata.m
Labels: Matlab, bug fix

#780 Urgent: require numpy < 2.0
  pyat/at/matching/matching.py
  pyat/at/physics/linear.py
  pyproject.toml
Labels: Python, bug fix

#783 Also scaling families in tune and chromaticity fits
  pyat/at/matching/globalfit.py
Labels: enhancement, Python

#778 Regression bug from PR #774: beam_current lattice attribute not propagated correctly
  atintegrators/BeamLoadingCavityPass.c
  atintegrators/atimplib.c
  pyat/at/lattice/lattice_object.py
  pyat/examples/CollectiveEffects/BeamLoading.py
  pyat/examples/CollectiveEffects/LCBI_run.py
  pyat/examples/CollectiveEffects/LongDistribution.py
  pyat/examples/CollectiveEffects/TRW_run.py
  pyat/test/test_collective.py
Labels: Python, bug fix

#773 Add momap multirefpts
  atmat/atphysics/TouschekPiwinski/MomAperture_Project2Start.m
  pyat/at/acceptance/__init__.py
  pyat/at/acceptance/momap_alternative.py
Labels: enhancement, Matlab, Python

#785 numpy 2.0 support
  .github/workflows/build-python-wheels.yml
  .github/workflows/matlab-tests.yml
  atmat/attests/githubrun.m
  atmat/attests/githubsetup.m
  pyat/at.c
  pyat/at/load/matfile.py
  pyat/at/load/reprfile.py
  pyat/at/load/utils.py
  pyproject.toml
Labels: enhancement, Python, C

#791 Fix load mat
  pyat/at/load/matfile.py
  pyproject.toml
Labels: Python, bug fix

#786 Update momentum aperture matlab
  atmat/atphysics/TouschekPiwinski/MomAperture_allRing.m
  atmat/atphysics/TouschekPiwinski/momentum_aperture_at.m
Labels: enhancement, Matlab

#789 add check_6d in findorbit4 and atlinopt4
  atmat/atdemos/atmatchExamples/ExampleATMATCH/getDispersion.m
  atmat/atphysics/LinearOptics/atlinopt.m
  atmat/atphysics/LinearOptics/atlinopt4.m
  atmat/atphysics/LinearOptics/atlinopt6.m
  atmat/atphysics/LinearOptics/findm44.m
  atmat/atphysics/LongitudinalDynamics/atsetcavity.m
  atmat/atphysics/LongitudinalDynamics/mcf.m
  atmat/atphysics/NonLinearDynamics/atnuampl.m
  atmat/atphysics/Orbit/findorbit4.m
  atmat/atphysics/Orbit/findsyncorbit.m
  atmat/atphysics/Radiation/check_6d.m
  atmat/atphysics/TuneAndChromaticity/tunechrom.m
  atmat/atphysics/findrespm.m
  atmat/attests/pytests.m
  atmat/lattice/atfastring.m
  atmat/pubtools/LatticeTuningFunctions/correction/response_matrix/findrespmat.m
  atmat/pubtools/LatticeTuningFunctions/errors/BPMerrors/testerr.m
  atmat/pubtools/LatticeTuningFunctions/errors/Survey/testerr.m
  atmat/pubtools/LatticeTuningFunctions/errors/findorbit4Err.m
Labels: enhancement, Matlab
