Repository atcollab/at, pull requests merged in 2024-09, with the labels that each got.

#823 Bug fix in atavedata
  atmat/atphysics/atavedata.m
  atmat/attests/pytests.m
  pyat/test_matlab/test_cmp_avlinopt.py
Labels: Matlab, bug fix

#827 add units and example of use to help
  atmat/atphysics/Radiation/atsetenergy.m
Labels: enhancement, Matlab

#830 matlab ohmienvelope add help message; add check_6d
  atmat/atphysics/Radiation/ohmienvelope.m
Labels: enhancement, Matlab

#824 Fix error messages in load_madx
  pyat/at/load/file_input.py
  pyat/at/load/mad8.py
  pyat/at/load/madx.py
  pyat/at/load/matfile.py
Labels: Python, bug fix

#822 Fix wiggler radiation
  atintegrators/gwigR.c
  atmat/atmexall.m
  atmat/atphysics/Radiation/FDW.c
  pyat/at/lattice/elements.py
  pyat/at/physics/__init__.py
  pyat/at/physics/radiation.py
  pyat/at/physics/wiggdiffmatrix.pyi
  setup.py
Labels: enhancement, Matlab, Python, bug fix

#831 Fix handling of JSON files when harmonic_number is undefined
  atmat/lattice/atSetRingProperties.m
  atmat/lattice/atloadlattice.m
  pyat/at/lattice/lattice_object.py
Labels: Matlab, Python, bug fix

#832 Fix saving lattices in m-files
  pyat/at/load/madx.py
  pyat/at/load/matfile.py
Labels: Python, bug fix
