Repository atcollab/at, pull requests merged in 2024-07, with the labels that each got.

#794 New test of the average optics values
  .github/workflows/matlab-tests.yml
  atmat/atphysics/atavedata.m
  atmat/attests/pytests.m
  pyat/at/physics/linear.py
Labels: Matlab, Python, bug fix

#770 Load MAD-X files
  docs/conf.py
  docs/p/api/at.load.mad8.rst
  docs/p/api/at.load.madx.rst
  pyat/at/constants.py
  pyat/at/lattice/particle_object.py
  pyat/at/load/__init__.py
  pyat/at/load/file_input.py
  pyat/at/load/mad8.py
  pyat/at/load/madx.py
  pyat/test/test_file_parser.py
  pyat/test/test_load_save.py
Labels: enhancement, Python

#738 Observable objects
  docs/p/index.rst
  docs/p/notebooks/observables.ipynb
  pyat/at/__init__.py
  pyat/at/latticetools/__init__.py
  pyat/at/latticetools/observablelist.py
  pyat/at/latticetools/observables.py
  pyat/test/test_observables.py
Labels: enhancement, Python

#802 use _Complex_I instead of I
  atintegrators/atimplib.c
Labels: bug, C

#797 Documentation improvement
  docs/p/howto/Installation.rst
  pyat/at/physics/linear.py
Labels: enhancement, Python

#798 Fix atpass error handling
  pyat/at.c
  pyat/at/tracking/atpass.pyi
  pyat/test/test_atpass.py
Labels: Python, bug fix, C
