Repository atcollab/at, pull requests merged in 2025-01, with the labels that each got.

#882 Fix OpenMP compilation
  atintegrators/BndMPoleSymplectic4RadPass.c
  atintegrators/ExactMultipoleRadPass.c
  atintegrators/StrMPoleSymplectic4RadPass.c
Labels: bug fix, C

#884 Update of Matlab physical constants to CODADA 2022
  atmat/atphysics/PhysConstant.m
Labels: Matlab

#881 remove seed from `atQuantumDiff.m` help
  atmat/lattice/element_creation/atQuantDiff.m
Labels: enhancement, Matlab

#889 Improvement of AT build process
  .github/workflows/matlab-tests.yml
  atintegrators/passFunctionMAC.map
  atintegrators/passFunctionMAC.mapext
  atintegrators/trackFunctionMAC.map
  atintegrators/trackFunctionMAC.mapext
  atmat/atmexall.m
  atmat/atphysics/TuneAndChromaticity/findtune.m
  atmat/atphysics/atavedata.m
  atmat/attests/githubsetup.m
  atmat/attests/pytests.m
  setup.py
Labels: enhancement, Matlab, Python

#888 Improve radiation_parameters
  atmat/atphysics/ParameterSummaryFunctions/atsummary.m
  atmat/lattice/element_creation/atenergyloss.m
  pyat/at/lattice/elements.py
  pyat/at/physics/radiation.py
Labels: Matlab, Python, bug fix

#891 Fix OpenMP compilation bug
  atmat/atmexall.m
  setup.py
Labels: Matlab, Python, bug fix
