Repository atcollab/at, pull requests merged in 2025-08, with the labels that each got.

#961 Add `CHROMATIC2` to pyat `get_rdts`
  pyat/at/physics/linear.py
  pyat/at/physics/rdt.py
  pyat/test/test_physics.py
Labels: enhancement, Python

#964 Adding the new CHROMATIC2 RDTs to the RDT Observables
  pyat/at/latticetools/rdt_observable.py
Labels: enhancement, Python

#975 FIx .mat files for sextupoles
  pyat/at/lattice/elements/magnet_elements.py
Labels: Python, bug fix

#976 Add constant wake potentials to wakefield pass
  atintegrators/WakeFieldPass.c
  atintegrators/atimplib.c
  pyat/at/collective/wake_elements.py
  pyat/at/collective/wake_object.py
Labels: enhancement, WIP
